2024-03-04 13:05:47,240: root: INFO: MLTrader : Executing the initialize lifecycle method
2024-03-04 13:05:47,468: alpaca_trade_api.stream: ERROR: error during websocket communication: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
Traceback (most recent call last):
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/alpaca_trade_api/stream.py", line 722, in _run_forever
    await self._start_ws()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/alpaca_trade_api/stream.py", line 682, in _start_ws
    await self._connect()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/alpaca_trade_api/stream.py", line 632, in _connect
    self._ws = await websockets.connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/websockets/legacy/client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1146, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1179, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
2024-03-04 13:05:47,497: alpaca_trade_api.stream: INFO: starting trading websocket connection
2024-03-04 13:05:47,771: root: INFO: Current backtesting datetime 2023-12-15 08:30:00-05:00
2024-03-04 13:05:47,772: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-03-04 13:05:47,771: alpaca_trade_api.stream: ERROR: error during websocket communication: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
Traceback (most recent call last):
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/alpaca_trade_api/stream.py", line 722, in _run_forever
    await self._start_ws()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/alpaca_trade_api/stream.py", line 682, in _start_ws
    await self._connect()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/alpaca_trade_api/stream.py", line 632, in _connect
    self._ws = await websockets.connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/websockets/legacy/client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1146, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1179, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
2024-03-04 13:05:47,773: root: INFO: Current backtesting datetime 2023-12-15 09:30:00-05:00
2024-03-04 13:05:47,773: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-03-04 13:05:47,773: root: INFO: MLTrader : Executing the on_trading_iteration lifecycle method at 2024-03-04 13:05:47
2024-03-04 13:05:47,773: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-03-04 13:05:47,774: root: ERROR: Traceback (most recent call last):
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Programming_Project/alpaca_test.py", line 24, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-03-04 13:05:47,774: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-03-04 13:05:47,775: root: INFO: MLTrader : Sleeping for 86400 seconds
2024-03-04 13:05:47,775: root: INFO: Current backtesting datetime 2023-12-16 09:30:00-05:00
2024-03-04 13:05:47,775: root: INFO: Current backtesting datetime 2023-12-18 08:30:00-05:00
2024-03-04 13:05:47,775: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-03-04 13:05:47,775: root: INFO: Current backtesting datetime 2023-12-18 09:30:00-05:00
2024-03-04 13:05:47,776: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-03-04 13:05:47,776: root: INFO: MLTrader : Executing the on_trading_iteration lifecycle method at 2024-03-04 13:05:47
2024-03-04 13:05:47,776: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-03-04 13:05:47,776: root: ERROR: Traceback (most recent call last):
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Programming_Project/alpaca_test.py", line 24, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-03-04 13:05:47,776: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-03-04 13:05:47,777: root: INFO: MLTrader : Sleeping for 86400 seconds
2024-03-04 13:05:47,777: root: INFO: Current backtesting datetime 2023-12-19 09:30:00-05:00
2024-03-04 13:05:47,777: root: INFO: Current backtesting datetime 2023-12-19 08:30:00-05:00
2024-03-04 13:05:47,777: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-03-04 13:05:47,778: root: INFO: Current backtesting datetime 2023-12-19 09:30:00-05:00
2024-03-04 13:05:47,778: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-03-04 13:05:47,778: root: INFO: MLTrader : Executing the on_trading_iteration lifecycle method at 2024-03-04 13:05:47
2024-03-04 13:05:47,778: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-03-04 13:05:47,778: root: ERROR: Traceback (most recent call last):
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Programming_Project/alpaca_test.py", line 24, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-03-04 13:05:47,778: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-03-04 13:05:47,779: root: INFO: MLTrader : Sleeping for 86400 seconds
2024-03-04 13:05:47,779: root: INFO: Current backtesting datetime 2023-12-20 09:30:00-05:00
2024-03-04 13:05:47,779: root: INFO: Current backtesting datetime 2023-12-20 08:30:00-05:00
2024-03-04 13:05:47,779: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-03-04 13:05:47,779: root: INFO: Current backtesting datetime 2023-12-20 09:30:00-05:00
2024-03-04 13:05:47,779: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-03-04 13:05:47,780: root: INFO: MLTrader : Executing the on_trading_iteration lifecycle method at 2024-03-04 13:05:47
2024-03-04 13:05:47,780: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-03-04 13:05:47,780: root: ERROR: Traceback (most recent call last):
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Programming_Project/alpaca_test.py", line 24, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-03-04 13:05:47,780: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-03-04 13:05:47,780: root: INFO: MLTrader : Sleeping for 86400 seconds
2024-03-04 13:05:47,780: root: INFO: Current backtesting datetime 2023-12-21 09:30:00-05:00
2024-03-04 13:05:47,781: root: INFO: Current backtesting datetime 2023-12-21 08:30:00-05:00
2024-03-04 13:05:47,781: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-03-04 13:05:47,781: root: INFO: Current backtesting datetime 2023-12-21 09:30:00-05:00
2024-03-04 13:05:47,781: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-03-04 13:05:47,781: root: INFO: MLTrader : Executing the on_trading_iteration lifecycle method at 2024-03-04 13:05:47
2024-03-04 13:05:47,782: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-03-04 13:05:47,782: root: ERROR: Traceback (most recent call last):
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Programming_Project/alpaca_test.py", line 24, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-03-04 13:05:47,782: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-03-04 13:05:47,782: root: INFO: MLTrader : Sleeping for 86400 seconds
2024-03-04 13:05:47,782: root: INFO: Current backtesting datetime 2023-12-22 09:30:00-05:00
2024-03-04 13:05:47,782: root: INFO: Current backtesting datetime 2023-12-22 08:30:00-05:00
2024-03-04 13:05:47,783: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-03-04 13:05:47,783: root: INFO: Current backtesting datetime 2023-12-22 09:30:00-05:00
2024-03-04 13:05:47,783: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-03-04 13:05:47,783: root: INFO: MLTrader : Executing the on_trading_iteration lifecycle method at 2024-03-04 13:05:47
2024-03-04 13:05:47,784: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-03-04 13:05:47,784: alpaca_trade_api.stream: INFO: starting trading websocket connection
2024-03-04 13:05:47,784: root: ERROR: Traceback (most recent call last):
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Programming_Project/alpaca_test.py", line 24, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-03-04 13:05:47,784: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-03-04 13:05:47,784: root: INFO: MLTrader : Sleeping for 86400 seconds
2024-03-04 13:05:47,784: root: INFO: Current backtesting datetime 2023-12-23 09:30:00-05:00
2024-03-04 13:05:47,785: root: INFO: Current backtesting datetime 2023-12-26 08:30:00-05:00
2024-03-04 13:05:47,785: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-03-04 13:05:47,785: root: INFO: Current backtesting datetime 2023-12-26 09:30:00-05:00
2024-03-04 13:05:47,785: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-03-04 13:05:47,786: root: INFO: MLTrader : Executing the on_trading_iteration lifecycle method at 2024-03-04 13:05:47
2024-03-04 13:05:47,786: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-03-04 13:05:47,786: root: ERROR: Traceback (most recent call last):
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Programming_Project/alpaca_test.py", line 24, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-03-04 13:05:47,786: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-03-04 13:05:47,787: root: INFO: MLTrader : Sleeping for 86400 seconds
2024-03-04 13:05:47,787: root: INFO: Current backtesting datetime 2023-12-27 09:30:00-05:00
2024-03-04 13:05:47,787: root: INFO: Current backtesting datetime 2023-12-27 08:30:00-05:00
2024-03-04 13:05:47,787: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-03-04 13:05:47,787: root: INFO: Current backtesting datetime 2023-12-27 09:30:00-05:00
2024-03-04 13:05:47,787: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-03-04 13:05:47,788: root: INFO: MLTrader : Executing the on_trading_iteration lifecycle method at 2024-03-04 13:05:47
2024-03-04 13:05:47,788: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-03-04 13:05:47,788: root: ERROR: Traceback (most recent call last):
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Programming_Project/alpaca_test.py", line 24, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-03-04 13:05:47,788: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-03-04 13:05:47,788: root: INFO: MLTrader : Sleeping for 86400 seconds
2024-03-04 13:05:47,788: root: INFO: Current backtesting datetime 2023-12-28 09:30:00-05:00
2024-03-04 13:05:47,789: root: INFO: Current backtesting datetime 2023-12-28 08:30:00-05:00
2024-03-04 13:05:47,789: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-03-04 13:05:47,789: root: INFO: Current backtesting datetime 2023-12-28 09:30:00-05:00
2024-03-04 13:05:47,789: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-03-04 13:05:47,789: root: INFO: MLTrader : Executing the on_trading_iteration lifecycle method at 2024-03-04 13:05:47
2024-03-04 13:05:47,789: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-03-04 13:05:47,790: root: ERROR: Traceback (most recent call last):
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Programming_Project/alpaca_test.py", line 24, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-03-04 13:05:47,790: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-03-04 13:05:47,790: root: INFO: MLTrader : Sleeping for 86400 seconds
2024-03-04 13:05:47,790: root: INFO: Current backtesting datetime 2023-12-29 09:30:00-05:00
2024-03-04 13:05:47,790: root: INFO: Current backtesting datetime 2023-12-29 08:30:00-05:00
2024-03-04 13:05:47,790: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-03-04 13:05:47,791: root: INFO: Current backtesting datetime 2023-12-29 09:30:00-05:00
2024-03-04 13:05:47,791: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-03-04 13:05:47,791: root: INFO: MLTrader : Executing the on_trading_iteration lifecycle method at 2024-03-04 13:05:47
2024-03-04 13:05:47,791: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-03-04 13:05:47,792: root: ERROR: Traceback (most recent call last):
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Session 5/venv/Programming_Project/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/PycharmProjects/Programming_Project/alpaca_test.py", line 24, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-03-04 13:05:47,792: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-03-04 13:05:47,792: root: INFO: MLTrader : Sleeping for 86400 seconds
2024-03-04 13:05:47,792: root: INFO: Current backtesting datetime 2023-12-30 09:30:00-05:00
2024-03-04 13:05:47,792: root: INFO: Current backtesting datetime 2024-01-02 08:30:00-05:00
2024-03-04 13:05:47,792: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-03-04 13:05:47,792: root: INFO: Current backtesting datetime 2024-01-02 09:30:00-05:00
2024-03-04 13:05:47,792: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-03-04 13:05:47,793: root: INFO: Current backtesting datetime 2024-01-02 15:55:00-05:00
2024-03-04 13:05:47,793: root: INFO: MLTrader : Executing the before_market_closes lifecycle method
2024-03-04 13:05:47,793: root: INFO: Current backtesting datetime 2024-01-02 16:00:00-05:00
2024-03-04 13:05:47,793: root: INFO: MLTrader : Executing the after_market_closes lifecycle method
2024-03-04 13:05:47,793: root: INFO: MLTrader : Executing the on_strategy_end lifecycle method
2024-03-04 13:05:47,793: backtest_stats: INFO: Backtest took 0:00:00.554168 for a speed of 0.000
2024-03-04 13:05:47,793: root: WARNING: Cannot plot returns because the strategy returns are missing
2024-03-04 13:05:47,866: root: WARNING: Cannot create a tearsheet because the strategy returns are missing
